#!/bin/bash

function set_IP_port() {

  read -p "Veuillez entrer le port : " port
  read -p "Veuillez entrer l'IP : " ip

  echo "Le port défini est : $port"
  echo "L'IP définie est : $ip"

  export IP_SERVER ip
  export PORT_SERVER port

  return 0
}

set_IP_port


